Repository googleapis/python-workflows, pull requests merged in 2021-01, with the labels that each got.

#17 chore: update templates
  LICENSE
  docs/_static/custom.css
  synth.metadata
Labels: api: workflows, cla: yes, context: full

#18 chore(python): skip docfx in main presubmit
  .kokoro/build.sh
  .kokoro/docs/docs-presubmit.cfg
  .trampolinerc
  noxfile.py
  synth.metadata
Labels: api: workflows, cla: yes, context: full

#16 feat: add from_service_account_info factory and fix docstring references
  .coveragerc
  docs/executions_v1beta/executions.rst
  docs/executions_v1beta/services.rst
  docs/executions_v1beta/types.rst
  docs/workflows_v1beta/services.rst
  docs/workflows_v1beta/types.rst
  docs/workflows_v1beta/workflows.rst
  google/cloud/workflows/executions_v1beta/services/executions/async_client.py
  google/cloud/workflows/executions_v1beta/services/executions/client.py
  google/cloud/workflows/executions_v1beta/services/executions/pagers.py
  google/cloud/workflows/executions_v1beta/types/executions.py
  google/cloud/workflows_v1beta/services/workflows/async_client.py
  google/cloud/workflows_v1beta/services/workflows/client.py
  google/cloud/workflows_v1beta/services/workflows/pagers.py
  google/cloud/workflows_v1beta/types/workflows.py
  synth.metadata
  tests/unit/gapic/executions_v1beta/test_executions.py
  tests/unit/gapic/workflows_v1beta/test_workflows.py
Labels: api: workflows, cla: yes, context: full

#20 chore: update templates
  .kokoro/docs/docs-presubmit.cfg
  .trampolinerc
  synth.metadata
  workflows-v1beta-py.tar.gz
Labels: api: workflows, cla: yes, context: none

#26 build: migrate to flakybot
  .kokoro/test-samples.sh
  .kokoro/trampoline_v2.sh
Labels: api: workflows, cla: yes
