Repository googleapis/python-workflows, pull requests merged in 2021-04, with the labels that each got.

#35 chore: start obsoelte file tracking
  synth.metadata
Labels: api: workflows, automerge, cla: yes, context: full

#39 chore: Fix formatting of synth.metadata
  synth.metadata
Labels: api: workflows, automerge, cla: yes

#40 chore: prevent normalization of semver versioning
  setup.py
Labels: api: workflows, cla: yes

#42 chore(revert): revert preventing normalization
  setup.py
Labels: api: workflows, cla: yes

#44 chore: use `gcp-sphinx-docfx-yaml`
  noxfile.py
Labels: api: workflows, cla: yes
